CREATE TABLE [GasketPurchaseTransactions] (
  [ITEM_NUMBER] VARCHAR (12),
  [REFERENCE_NO] VARCHAR (12),
  [TRANS_DATE] VARCHAR (8),
  [TRANS_QTY] DECIMAL (7, 0),
  [TRANS_TYPE] VARCHAR (1),
  [CUR_ACT_COST] DECIMAL (11, 5)
)
