CREATE TABLE [JCRepairKits] (
  [P/N] VARCHAR (255),
  [Title] VARCHAR (255),
  [Qty] DOUBLE ,
  [UM] VARCHAR (255),
  [ID] AUTOINCREMENT CONSTRAINT [ID] PRIMARY KEY  UNIQUE  NOT NULL ,
  [Total Qty] DOUBLE 
)
