CREATE TABLE [MOList] (
  [SO] VARCHAR (255),
  [MO] VARCHAR (255),
  [MO Type] VARCHAR (4),
  [MO No] VARCHAR (11),
  [Date] VARCHAR (8),
  [BOMDate] VARCHAR (8),
  [BOMVersion] VARCHAR (4),
  [Item] VARCHAR (20),
  [Unit] VARCHAR (4),
  [Plan Start Date] VARCHAR (8),
  [Plan Complete Date] VARCHAR (8),
  [Status] VARCHAR (1),
  [Actual Start Date] VARCHAR (8),
  [Approve Indicator] VARCHAR (1),
  [Actual Complete Date] VARCHAR (8),
  [Plan Quantity] DECIMAL (15, 6),
  [Material Issued Kit Quantity] DECIMAL (15, 6),
  [Completed Quantity] DECIMAL (15, 6),
  [Scrap Quantity] DECIMAL (15, 6),
  [Plant] VARCHAR (6),
  [Receipt Warehouse] VARCHAR (10),
  [Work Center] VARCHAR (10),
  [Subcontract Price] DECIMAL (17, 8),
  [Subcontract Unit] VARCHAR (4),
  [Source MO Type] VARCHAR (4),
  [Source MO No] VARCHAR (11),
  [Order Type] VARCHAR (4),
  [Sales Order Number] VARCHAR (11),
  [Order Sequence] VARCHAR (4),
  [Remark] VARCHAR (255),
  [Character] VARCHAR (1),
  [Print Times] DECIMAL (1, 0),
  [Subcontractor] VARCHAR (10),
  [Plan Batch No] VARCHAR (20),
  [Item  Description] VARCHAR (60),
  [Item Spec] VARCHAR (60),
  [Plan Start Date2] VARCHAR (1),
  [Plan Complete Date2] VARCHAR (1),
  [Actual Start Date2] VARCHAR (1),
  [Actual Complete Date2] VARCHAR (1),
  [Approve Date] VARCHAR (8),
  [Approver] VARCHAR (10),
  [Currency] VARCHAR (4),
  [Exchange Rate] DECIMAL (10, 7),
  [Urgent] VARCHAR (1),
  [Plan Packing Quantity] DECIMAL (15, 6),
  [Completed Packing Quantity] DECIMAL (15, 6),
  [Scrap Packing Quantity] DECIMAL (15, 6),
  [Packing Unit] VARCHAR (4),
  [E-Approval Status] VARCHAR (1),
  [Remark 1] VARCHAR (100),
  [Remark 2] VARCHAR (100),
  [Remark 3] VARCHAR (100),
  [Remark 4] VARCHAR (100),
  [Transfer Times] DECIMAL (1, 0),
  [Tax Type] VARCHAR (1),
  [Subcontract Quantity] DECIMAL (15, 6),
  [Production Lot] VARCHAR (20),
  [Lot Description] VARCHAR (80),
  [Production Permission] VARCHAR (1),
  [Destroyed Quantity] DECIMAL (15, 6),
  [Destroyed Packing Quantity] DECIMAL (15, 6),
  [Print Times of Routing Slip] DECIMAL (1, 0),
  [Required Date] VARCHAR (8),
  [Department] VARCHAR (6),
  [Payment Term No] VARCHAR (6),
  [Tax Rate] DECIMAL (5, 4),
  [Configuration Code] VARCHAR (15),
  [Configuration Sequence] VARCHAR (4)
)
