CREATE TABLE [SOList] (
  [SO] VARCHAR (255),
  [SODate] VARCHAR (8),
  [Order Type] VARCHAR (4),
  [Order No] VARCHAR (11),
  [Sequence Number] VARCHAR (4),
  [Item] VARCHAR (20),
  [Item Description] VARCHAR (60),
  [Specification] VARCHAR (60),
  [Warehouse] VARCHAR (10),
  [Quantity] DECIMAL (15, 6),
  [Delivered Quantity] DECIMAL (15, 6),
  [Unit] VARCHAR (4),
  [Price] DECIMAL (17, 8),
  [Amount] DECIMAL (15, 2),
  [Plan Delivery Date] VARCHAR (8),
  [Customer Item] VARCHAR (20),
  [Sales Forecast Number] VARCHAR (11),
  [Close] VARCHAR (1),
  [Pre-Document-Order Type] VARCHAR (4),
  [Pre-Document-Order No] VARCHAR (11),
  [Pre-Document-Sequence Number] VARCHAR (4),
  [Remark] VARCHAR (255),
  [Approval Indicator] VARCHAR (1),
  [Inventory Quantity] DECIMAL (15, 6),
  [Small Unit] VARCHAR (4),
  [Largess Quantity] DECIMAL (15, 6),
  [Largess Delivered Quantity] DECIMAL (15, 6),
  [Discount Rate] DECIMAL (5, 4),
  [Item No] VARCHAR (20),
  [Forecast Sequence] VARCHAR (4),
  [Packing Method] VARCHAR (3),
  [Gross Weight(Kg)] DECIMAL (8, 3),
  [Volume(CUFT)] DECIMAL (8, 3),
  [Packing Quantity] DECIMAL (15, 6),
  [Delivered Packing Quantity] DECIMAL (15, 6),
  [Largess Packing Quantity] DECIMAL (15, 6),
  [Largess Delivered Packing Quantity] DECIMAL (15, 6),
  [Packing Unit] VARCHAR (4),
  [Tax Rate] DECIMAL (5, 4),
  [Amount Un-include Tax] DECIMAL (15, 2),
  [Tax] DECIMAL (15, 2),
  [Pieces Per] DECIMAL (15, 6),
  [Pieces] DECIMAL (15, 6),
  [Wholesale Price] DECIMAL (17, 8),
  [Retail Price] DECIMAL (17, 8),
  [Issue Quantity For Sales] DECIMAL (15, 6),
  [Issue Packing Quantity For Sales] DECIMAL (15, 6),
  [Original Customer] VARCHAR (10),
  [Configuration Code] VARCHAR (15),
  [Simulation unit cost] DECIMAL (17, 8),
  [Simulation Cost] DECIMAL (15, 2),
  [Estimated Gross Profit Ratio] DECIMAL (7, 4),
  [Estimated Gross Profit] DECIMAL (15, 2)
)
