CREATE TABLE [tblTempCompareMOLinesToEngBOM] (
  [Parent] VARCHAR (20),
  [Parent Descrip] VARCHAR (255),
  [ChildFromMOLines] VARCHAR (20),
  [Child] VARCHAR (255),
  [Child Descrip] VARCHAR (255),
  [Required Quantity] DECIMAL (15, 6),
  [Unit] VARCHAR (4),
  [Actual Material Issue] VARCHAR (8),
  [EngReqdQty] DOUBLE ,
  [UNUseUnits] VARCHAR (255),
  [Plan Start Date] VARCHAR (8),
  [ConversionFactorKey] VARCHAR (255),
  [MO Type] VARCHAR (4),
  [MO No] VARCHAR (11),
  [Status] VARCHAR (1),
  [Plan Quantity] DECIMAL (15, 6),
  [SumOfQty Per Assy] DOUBLE ,
  [ConversionFactor] DOUBLE ,
  [MOLinesReqdQtyInUNUSeUnits] DOUBLE ,
  [ScrapFactor] DOUBLE ,
  [EngReqdQtyWithScrap] DOUBLE ,
  [Qty Per] DECIMAL (15, 6),
  [Ratio] DOUBLE ,
  [CorrectedChildFromMOLines] VARCHAR (50)
)
