dbMemo "SQL" ="SELECT BOMLinesThree.[Parent Item], BOMLinesThree.[Sub Item], BOMLinesThree.[Qty"
    " Per], Items.[Item Property], Items.[Low level Code]\015\012FROM ManufacturedIte"
    "msWithLLCEqualTo00 INNER JOIN (BOMLinesThree INNER JOIN Items ON BOMLinesThree.["
    "Sub Item]=Items.Item) ON ManufacturedItemsWithLLCEqualTo00.Item=BOMLinesThree.[P"
    "arent Item]\015\012WHERE (((Items.[Low level Code])<>\"99\"));\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
