dbMemo "SQL" ="INSERT INTO tblTempCompareERPBOMtoPNVBOM ( Parent, [Parent Description], [ERP Co"
    "mponent], [PNV Component], [Child Description], [ERP Qty], [ERP Stock Unit], [PN"
    "V Qty], [PNV UNUseUnit] )\015\012SELECT BOMLines3WithUnits2.[Parent Item], BOMLi"
    "nes3WithUnits2.[Parent Description], BOMLines3WithUnits2.[Sub Item], BOM1Summary"
    ".Child, BOMLines3WithUnits2.[Child Description], BOMLines3WithUnits2.[Qty Per], "
    "BOMLines3WithUnits2.[Stock Unit], BOM1Summary.[SumOfQty Per Assy], BOM1Summary.U"
    "NUseUnits\015\012FROM BOMLines3WithUnits2 LEFT JOIN BOM1Summary ON (BOMLines3Wit"
    "hUnits2.[Sub Item]=BOM1Summary.Child) AND (BOMLines3WithUnits2.[Parent Item]=BOM"
    "1Summary.Parent)\015\012WHERE (((BOMLines3WithUnits2.[Parent Item]) Like \"DC00*"
    "\") AND ((BOM1Summary.Child) Is Null));\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "UseTransaction" ="-1"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
