dbMemo "SQL" ="SELECT BOMLinesThree.[Sub Item], SalesDeliveryLines.Item, SalesDeliveryHeaders.["
    "Delivery Date], SalesDeliveryLines.Quantity, SalesDeliveryLines.[Inventory Quant"
    "ity], SalesDeliveryLines.[Order Type2], SalesDeliveryLines.[Sales Order Number],"
    " SalesDeliveryLines.[Order Sequence]\015\012FROM BOMLinesThree INNER JOIN (Sales"
    "DeliveryLines INNER JOIN SalesDeliveryHeaders ON (SalesDeliveryLines.[Order No]="
    "SalesDeliveryHeaders.[Order No]) AND (SalesDeliveryLines.[Order Type]=SalesDeliv"
    "eryHeaders.[Order Type])) ON BOMLinesThree.[Parent Item]=SalesDeliveryLines.Item"
    "\015\012WHERE (((BOMLinesThree.[Sub Item])=Forms!MOOverIssue!Item))\015\012ORDER"
    " BY SalesDeliveryHeaders.[Delivery Date];\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
