dbMemo "SQL" ="SELECT MOLines.[MO Type], MOLines.[MO No], MOLines.Item, MOLines.[Required Quant"
    "ity], MOLines.[Issued Quantity], MOLines.[Actual Material Issue], MOHeaders.Item"
    ", MOHeaders.[Plan Quantity], MOHeaders.[Material Issued Kit Quantity], MOHeaders"
    ".[Completed Quantity], MOHeaders.[Scrap Quantity], MOHeaders.[Plan Start Date], "
    "MOHeaders.[Plan Complete Date], MOHeaders.Status, MOHeaders.[Actual Complete Dat"
    "e]\015\012FROM MOLines INNER JOIN MOHeaders ON (MOLines.[MO Type]=MOHeaders.[MO "
    "Type]) AND (MOLines.[MO No]=MOHeaders.[MO No])\015\012WHERE (((MOLines.[MO Type]"
    ") Like [MO Type begins?] & \"*\") AND ((MOLines.[MO No]) Like [MO Number begins?"
    "] & \"*\") AND ((MOLines.Item) Like [Child begins ?] & \"*\") AND ((MOHeaders.It"
    "em) Like [Parent Item begins with?] & \"*\"))\015\012ORDER BY MOLines.Item;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
